
name: finn_env
channels:
  - conda-forge
dependencies:
  - python==3.7
  - nipype<=1.7.0
  - pingouin<=0.5.0
  - pandas<=1.3.5
  - numpy<=1.21.5
  - scipy<=1.7.3
  - nilearn<=0.8.1
  - matplotlib<=3.5.1
  - seaborn<=0.11.2
  - nibabel<=3.2.1
  - jupyterlab<=3.2.5
  - notebook<=6.4.6
  - urllib3==1.26.15
  - joblib<=1.1.1
  - numba<=0.54.1
  - statsmodels<=0.13.1
  - scikit-learn<=1.0.1
  - pip
  - pybids
  - pip:
      - hcp-utils==0.1.0
      - niworkflows==1.4.4